### ISSUE TITLE
help

### ISSUE THREAD

**Issue by serpafi** [robjtede/sup-decode#37]
Hello,
I am contacting you for help on extracting images from a .sup file and if you have some time for me.
I'm working on the sup to srt conversion to integrate it into my TAO-MKV software written in "Autoit" and another open source which will also be on github.
I soon finished extracting the timestamp from the hex and all the OCR 5.0.x part is finished but I cannot find a tutorial or info to retrieve the bitmaps from the sup file and put them in png, jpg or again bmp.
Your help will be welcome.
thank you in advance
cordially

Sorry for my english, it's google translate :)

**Comment by robjtede** [comment]
I'm not sure this will do what you want as it is. There's no library component, it is only a GUI.

You can fork and change the code if you want to. It shouldn't be much work to make it save images.

**Comment by serpafi** [comment]
Thank you for your reply.
Unfortunately I know the autoit and batch language but not rust so I couldn't work on your code.
 
I quickly created a software in autoit to read hexadecimal and classify them under pcs, wds, pds, ods and end.
https://www.autoitscript.fr/forum/viewtopic.php?f=6&t=15587

sorry, what do you mean by PRs?

**Comment by robjtede** [comment]
> sorry, what do you mean by PRs?

https://github.com/robjtede/sup-decode/pulls

**Comment by serpafi** [comment]
ok I understood the PRs  
thank you
